import { Injectable, Logger } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import * as fs from 'fs';
import * as path from 'path';

export interface GenerationRequest {
  originalImageUrl: string;
  productName: string;
  productCategory: string;
  isWearable: boolean;
  imageType: string;
  platform: string;
  additionalPrompt?: string;
}

@Injectable()
export class ImagenService {
  private readonly logger = new Logger(ImagenService.name);
  private genAI: any;
  private model: any;

  constructor(private readonly config: ConfigService) {
    this.initSDK();
  }

  private async initSDK() {
    const apiKey = this.config.get<string>('GEMINI_API_KEY', '');
    if (!apiKey) {
      this.logger.warn('GEMINI_API_KEY not set — image generation will fail');
      return;
    }
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const { GoogleGenerativeAI } = require('@google/generative-ai');
    this.genAI = new GoogleGenerativeAI(apiKey);
    this.model = this.genAI.getGenerativeModel({
      model: 'gemini-2.5-flash-image',
      generationConfig: { responseModalities: ['IMAGE', 'TEXT'] },
    });
  }

  async generateImage(request: GenerationRequest): Promise<string> {
    if (!this.model) {
      throw new Error('Gemini SDK not initialized — check GEMINI_API_KEY');
    }

    const prompt = this.buildPrompt(request);
    const imagePart = this.resolveImagePart(request.originalImageUrl);

    this.logger.log(
      `Generating ${request.imageType} image for "${request.productName}"`,
    );

    const result = await this.model.generateContent([prompt, imagePart]);
    const response = result.response;

    const parts = response.candidates?.[0]?.content?.parts;
    if (!parts || parts.length === 0) {
      throw new Error('No content generated by Gemini API');
    }

    const generatedImagePart = parts.find((p: any) => p.inlineData);
    if (!generatedImagePart?.inlineData) {
      throw new Error('No image in Gemini response — got text only');
    }

    const mimeType = generatedImagePart.inlineData.mimeType || 'image/png';
    const base64 = generatedImagePart.inlineData.data;

    return `data:${mimeType};base64,${base64}`;
  }

  /**
   * Converts the original image URL (data URI or local URL) into an
   * inlineData part that the Gemini SDK expects.
   */
  private resolveImagePart(imageUrl: string): { inlineData: { data: string; mimeType: string } } {
    if (imageUrl.startsWith('data:')) {
      const match = imageUrl.match(/^data:([^;]+);base64,(.+)$/);
      if (!match) throw new Error('Invalid data URI for image');
      return { inlineData: { data: match[2], mimeType: match[1] } };
    }

    // Shouldn't happen after resolveExternalUrl, but handle gracefully
    throw new Error(
      'Image must be a data URI. Ensure StorageService.resolveExternalUrl was called.',
    );
  }

  private buildPrompt(request: GenerationRequest): string {
    const basePrompts: Record<string, string> = {
      main: `Generate a professional e-commerce product shot of this item. ` +
        `Place it on a clean, pure white studio background with realistic drop shadows. ` +
        `Bright, even commercial lighting. Product fills 85% of frame. For ${this.platformLabel(request.platform)}.`,
      lifestyle: `Place this product in a beautiful lifestyle setting. ` +
        `Natural lighting, aspirational context, high quality product photography. ` +
        `Make it look premium and desirable for ${this.platformLabel(request.platform)}.`,
      closeup: `Generate an extreme close-up detail shot of this product. ` +
        `Show texture, material quality, and craftsmanship. Macro photography style, ` +
        `studio lighting, white background.`,
      scale: `Show this product with a size reference for scale comparison. ` +
        `Clean product photography on white background, professional lighting.`,
      angle: `Photograph this product from a 45-degree angle showing depth and dimension. ` +
        `Professional product photography, white background, studio lighting.`,
      model: `Render this clothing item on a professional fashion model. ` +
        `Show only from the neck down to the feet; do not show the face. ` +
        `Natural lighting, high-end editorial look for ${this.platformLabel(request.platform)}.`,
    };

    let prompt = basePrompts[request.imageType] || basePrompts.main;

    if (request.additionalPrompt) {
      prompt += ` ${request.additionalPrompt}`;
    }

    return prompt;
  }

  private platformLabel(platform: string): string {
    const labels: Record<string, string> = {
      amazon: 'Amazon',
      flipkart: 'Flipkart',
      meesho: 'Meesho',
      ajio: 'AJIO',
      gumroad: 'Gumroad',
    };
    return labels[platform] || 'e-commerce';
  }
}
